# Generated by Django 2.0.5 on 2018-05-14 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_handler', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='platformuser',
            options={'verbose_name_plural': 'PlatformUsers'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name_plural': 'Projects'},
        ),
        migrations.RenameField(
            model_name='company',
            old_name='UUID',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='platformuser',
            old_name='UUID',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='UUID',
            new_name='uuid',
        ),
        migrations.AlterField(
            model_name='company',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='api_handler.PlatformUser'),
        ),
        migrations.AlterField(
            model_name='project',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api_handler.Company'),
        ),
    ]
