# Generated by Django 2.0.5 on 2018-05-14 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_handler', '0002_auto_20180514_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='uuid',
            field=models.UUIDField(unique=True),
        ),
        migrations.AlterField(
            model_name='platformuser',
            name='uuid',
            field=models.UUIDField(unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='uuid',
            field=models.UUIDField(unique=True),
        ),
    ]
