# Generated by Django 2.0.5 on 2018-05-15 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_handler', '0003_auto_20180514_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='user',
        ),
        migrations.RemoveField(
            model_name='project',
            name='company',
        ),
        migrations.AddField(
            model_name='platformuser',
            name='company_procore_id',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='company_uuid',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api_handler.PlatformUser'),
        ),
        migrations.AlterField(
            model_name='platformuser',
            name='procore_access_token',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
