# Generated by Django 2.0.5 on 2018-05-16 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_handler', '0004_auto_20180515_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True)),
                ('company_procore_id', models.CharField(max_length=64, null=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.RemoveField(
            model_name='platformuser',
            name='company_procore_id',
        ),
        migrations.RemoveField(
            model_name='platformuser',
            name='company_uuid',
        ),
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.AddField(
            model_name='platformuser',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PlatformUsers', to='api_handler.Company'),
        ),
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Projects', to='api_handler.Company'),
        ),
    ]
