# Generated by Django 2.0.5 on 2018-05-16 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_handler', '0005_auto_20180516_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_procore_id',
            new_name='procore_company_id',
        ),
        migrations.RemoveField(
            model_name='platformuser',
            name='procore_client_id',
        ),
        migrations.RemoveField(
            model_name='platformuser',
            name='procore_client_secret',
        ),
        migrations.AddField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='procore_user_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='platformuser',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platformusers', to='api_handler.Company'),
        ),
        migrations.AlterField(
            model_name='project',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api_handler.Company'),
        ),
    ]
