# Generated by Django 2.0.5 on 2018-05-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_handler', '0007_auto_20180516_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platformuser',
            old_name='procore_access_token',
            new_name='access_token',
        ),
        migrations.AddField(
            model_name='platformuser',
            name='access_token_created_at',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='access_token_expires_in',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='refresh_token',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
