# Generated by Django 2.0.5 on 2018-05-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_handler', '0008_auto_20180517_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='procore_company_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='platformuser',
            name='procore_user_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='procore_project_id',
            field=models.CharField(max_length=20),
        ),
    ]
